version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    ports:
      - 5432:5433
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nulprostir
volumes:
  db_volume:
