version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    links:
      - "postgres"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Hajaomija123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nulprostir
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_volume:
